version: '3'
volumes:
  dados:
networks:
  banco:
  web:
services:
  www:
    build: 
      context: .
      dockerfile: ./docker-images/www/Dockerfile
    ports: 
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - web
  db:
    build: 
      context: .
      dockerfile: ./docker-images/mysql/Dockerfile
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pga_lab
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senhadousuario
      MYSQL_ROOT_PASSWORD: senhadousuario
    volumes:
      - ./docker-images/mysql/dump:/docker-entrypoint-initdb.d
      - dados:/var/lib/mysql
    networks:
      - banco
  phpmyadmin:
    build: 
      context: .
      dockerfile:  ./docker-images/phpmyadmin/Dockerfile
    volumes:
      - dados
    environment:
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senhadousuario
      MYSQL_ROOT_PASSWORD: senhadousuario
    networks:
      - banco
      - web
